name: marchantia_hhdb
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - hhsuite=3.3.0
  - parallel             # for batch_query.sh
  - pandas               # parse .hhr into tabular form
  - matplotlib-base      # plot top hits + coverage map
